import json
import os

languages = {
    "en": {
        "dashboard": "Dashboard", "earnings": "Earnings", "incoming_jobs": "Incoming Jobs",
        "profile": "Profile", "availability": "Availability", "reviews": "Reviews", 
        "navigation": "Navigation", "logout": "Logout", "welcome": "Worker Dashboard",
        "performance_overview": "Welcome back! Here's your performance overview.", "total_jobs": "Total Jobs",
        "completed_jobs": "Completed Jobs", "pending_jobs": "Pending Jobs", "avg_rating": "Average Rating",
        "total_earnings": "Total Earnings", "quick_actions": "Quick Actions", "edit_profile": "Edit Profile",
        "set_availability": "Set Availability", "recent_jobs": "Recent Jobs", "view_all": "View All",
        "save_profile": "Save Profile", "full_name": "Full Name", "skills": "Skills", 
        "experience": "Experience", "hourly_rate": "Hourly Rate", "languages": "Languages", "bio": "Bio",
        "update_profile_desc": "Update your professional details to attract more clients.",
        "active_status": "Active Status", "available": "Available", "unavailable": "Unavailable",
        "offline": "Offline", "working_hours": "Preferred Working Hours", "save_settings": "Save Settings",
        "accept": "Accept", "reject": "Reject", "new_requests": "New service requests matching your skills.",
        "this_month": "This Month", "customer_reviews": "Customer Reviews", "verified": "VERIFIED",
        "customer": "Customer", "voice_command_hint": "Try saying 'Open Earnings'",
        "listening": "Listening...", "voice_not_supported": "Your browser does not support voice recognition.",
        "good_morning": "Good morning", "daily_overview": "Here's your daily overview",
        "receive_nearby_jobs": "You will receive nearby jobs", "currently_hidden": "You are currently hidden",
        "your_hub": "Your Hub", "view_stats": "View Stats", "todays_earnings": "Today's Earnings",
        "overall_rating": "Overall Rating", "on_the_way": "On the Way", "navigate": "Navigate",
        "nearby_jobs": "Nearby Jobs", "urgent": "Urgent", "distance": "distance", "min": "min",
        "arrival": "Arrival", "exit_trip": "Exit Trip", "minimize": "Minimize", "completed": "Completed"
    },
    "hi": {
        "dashboard": "डैशबोर्ड", "earnings": "कमाई", "incoming_jobs": "आने वाले जॉब",
        "profile": "प्रोफ़ाइल", "availability": "उपलब्धता", "reviews": "समीक्षाएं", 
        "navigation": "नेविगेशन", "logout": "लॉग आउट", "welcome": "वर्कर डैशबोर्ड",
        "performance_overview": "वापसी पर स्वागत है! यह आपकी प्रदर्शन रिपोर्ट है।", "total_jobs": "कुल जॉब",
        "completed_jobs": "पूरे किए गए जॉब", "pending_jobs": "लंबित जॉब", "avg_rating": "औसत रेटिंग",
        "total_earnings": "कुल कमाई", "quick_actions": "त्वरित क्रियाएं", "edit_profile": "प्रोफ़ाइल संपादित करें",
        "set_availability": "उपलब्धता दर्ज करें", "recent_jobs": "हाल के जॉब", "view_all": "सभी देखें",
        "save_profile": "प्रोफ़ाइल सहेजें", "full_name": "पूरा नाम", "skills": "कौशल", 
        "experience": "अनुभव", "hourly_rate": "प्रति घंटा दर", "languages": "भाषाएं", "bio": "परिचय",
        "update_profile_desc": "अधिक ग्राहक आकर्षित करने के लिए अपने विवरण अपडेट करें।",
        "active_status": "सक्रिय स्थिति", "available": "उपलब्ध", "unavailable": "अनुपलब्ध",
        "offline": "ऑफ़लाइन", "working_hours": "पसंदीदा काम के घंटे", "save_settings": "सेटिंग्स सहेजें",
        "accept": "स्वीकारें", "reject": "अस्वीकार करें", "new_requests": "आपके कौशल से मेल खाने वाले नए सेवा अनुरोध।",
        "this_month": "इस महीने", "customer_reviews": "ग्राहक समीक्षाएं", "verified": "सत्यापित",
        "customer": "ग्राहक", "voice_command_hint": "बोल कर देखें 'कमाई खोलें'",
        "listening": "सुन रहा हूँ...", "voice_not_supported": "आपका ब्राउज़र वॉयस को सपोर्ट नहीं करता।",
        "good_morning": "सुप्रभात", "daily_overview": "यहाँ आपका दैनिक अवलोकन है",
        "receive_nearby_jobs": "आपको आस-पास के काम मिलेंगे", "currently_hidden": "आप वर्तमान में छिपे हुए हैं",
        "your_hub": "आपका हब", "view_stats": "आंकड़े देखें", "todays_earnings": "आज की कमाई",
        "overall_rating": "कुल रेटिंग", "on_the_way": "रास्ते में", "navigate": "नेविगेट करें",
        "nearby_jobs": "आस-पास के काम", "urgent": "तत्काल", "distance": "दूरी", "min": "मिनट",
        "arrival": "आगमन", "exit_trip": "यात्रा समाप्त करें", "minimize": "छोटा करें", "completed": "पूर्ण"
    },
    "mr": {
        "dashboard": "डॅशबोर्ड", "earnings": "कमाई", "incoming_jobs": "येणारी कामे",
        "profile": "प्रोफाइल", "availability": "उपलब्धता", "reviews": "पुनरावलोकने", 
        "navigation": "नेव्हिगेशन", "logout": "लॉगआउट", "welcome": "वर्कर डॅशबोर्ड",
        "performance_overview": "परत आल्यावर स्वागत आहे! तुमचा कामगिरीचा अहवाल.", "total_jobs": "एकूण कामे",
        "completed_jobs": "पूर्ण झालेली कामे", "pending_jobs": "प्रलंबित कामे", "avg_rating": "सरासरी रेटिंग",
        "total_earnings": "एकूण कमाई", "quick_actions": "त्वरित क्रिया", "edit_profile": "प्रोफाइल संपादित करा",
        "set_availability": "उपलब्धता सेट करा", "recent_jobs": "अलीकडील कामे", "view_all": "सर्व पहा",
        "save_profile": "प्रोफाइल जतन करा", "full_name": "पूर्ण नाव", "skills": "कौशल्ये", 
        "experience": "अनुभव", "hourly_rate": "तासाचा दर", "languages": "भाषा", "bio": "परिचय",
        "update_profile_desc": "जास्त ग्राहकांना आकर्षित करण्यासाठी तुमचे प्रोफाइल अपडेट करा.",
        "active_status": "सक्रिय स्थिती", "available": "उपलब्ध", "unavailable": "अनुपलब्ध",
        "offline": "ऑफलाइन", "working_hours": "कामाचे प्राधान्य तास", "save_settings": "सेटिंग्ज सेव्ह करा",
        "accept": "स्वीकारा", "reject": "नाकारा", "new_requests": "तुमच्या कौशल्याशी जुळणाऱ्या नवीन विनंत्या.",
        "this_month": "या महिन्यात", "customer_reviews": "ग्राहक पुनरावलोकने", "verified": "सत्यापित",
        "customer": "ग्राहक", "voice_command_hint": "'कमाई उघडा' बोलून पहा",
        "listening": "ऐकत आहे...", "voice_not_supported": "तुमचा ब्राउझर व्हॉइस ला सपोर्ट करत नाही.",
        "good_morning": "शुभ प्रभात", "daily_overview": "येथे आपला दैनंदिन आढावा आहे",
        "receive_nearby_jobs": "आपल्याला जवळील कामे मिळतील", "currently_hidden": "तुम्ही सध्या लपलेले आहात",
        "your_hub": "तुमचे हब", "view_stats": "आकडेवारी पहा", "todays_earnings": "आजची कमाई",
        "overall_rating": "एकूण रेटिंग", "on_the_way": "वाटेवर", "navigate": "नेव्हिगेट करा",
        "nearby_jobs": "जवळील कामे", "urgent": "तातडीचे", "distance": "अंतर", "min": "मिनिट",
        "arrival": "आगमन", "exit_trip": "प्रवास समाप्त करा", "minimize": "लहान करा", "completed": "पूर्ण"
    },
    "te": {
        "dashboard": "డాష్‌బోర్డ్", "earnings": "ఆదాయం", "incoming_jobs": "వస్తున్న పనులు",
        "profile": "ప్రొఫైల్", "availability": "అందుబాటు", "reviews": "సమీక్షలు", 
        "navigation": "నావిగేషన్", "logout": "లాగ్అవుట్", "welcome": "వర్కర్ డాష్‌బోర్డ్",
        "performance_overview": "స్వాగతం! మీ పనితీరు నివేదిక ఇక్కడ ఉంది.", "total_jobs": "మొత్తం పనులు",
        "completed_jobs": "పూర్తయిన పనులు", "pending_jobs": "పెండింగ్ పనులు", "avg_rating": "సగటు రేటింగ్",
        "total_earnings": "మొత్తం ఆదాయం", "quick_actions": "త్వరిత చర్యలు", "edit_profile": "ప్రొఫైల్ సవరించండి",
        "set_availability": "అందుబాటు సెట్ చేయండి", "recent_jobs": "ఇటీవలి పనులు", "view_all": "అన్నీ చూడండి",
        "save_profile": "ప్రొఫైల్ సేవ్ చేయండి", "full_name": "పూర్తి పేరు", "skills": "నైపుణ్యాలు", 
        "experience": "అనుభవం", "hourly_rate": "గంటకు ధర", "languages": "భాషలు", "bio": "పరిచయం",
        "update_profile_desc": "మరింత మంది కస్టమర్లను ఆకర్షించడానికి మీ వివరాలను అప్‌డేట్ చేయండి.",
        "active_status": "సక్రియ స్థితి", "available": "అందుబాటులో ఉంది", "unavailable": "అందుబాటులో లేదు",
        "offline": "ఆఫ్‌లైన్", "working_hours": "పని వేళలు", "save_settings": "సెట్టింగులను సేవ్ చేయండి",
        "accept": "అంగీకరించు", "reject": "తిరస్కరించు", "new_requests": "మీ నైపుణ్యాలకు సరిపోయే కొత్త అభ్యర్థనలు.",
        "this_month": "ఈ నెల", "customer_reviews": "కస్టమర్ సమీక్షలు", "verified": "ధృవీకరించబడింది",
        "customer": "కస్టమర్", "voice_command_hint": "'ఆదాయం తెరవండి' అని చెప్పండి",
        "listening": "వింటున్నాను...", "voice_not_supported": "మీ బ్రౌజర్ వాయిస్‌కి మద్దతు ఇవ్వదు.",
        "good_morning": "శుభోదయం", "daily_overview": "ఇది మీ రోజువారీ అవలోకనం",
        "receive_nearby_jobs": "మీకు సమీప పనులు అందుతాయి", "currently_hidden": "మీరు ప్రస్తుతం ఆఫ్‌లైన్ లో ఉన్నారు",
        "your_hub": "మీ హబ్", "view_stats": "గణాంకాలు చూడండి", "todays_earnings": "నేటి ఆదాయం",
        "overall_rating": "మొత్తం రేటింగ్", "on_the_way": "దారిలో", "navigate": "నావిగేట్ చేయండి",
        "nearby_jobs": "సమీప పనులు", "urgent": "అత్యవసరం", "distance": "దూరం", "min": "నిమిషం",
        "arrival": "రాక", "exit_trip": "ట్రిప్ ఎగ్జిట్", "minimize": "కనిష్టీకరించు", "completed": "పూర్తయింది"
    },
    "ta": {
        "dashboard": "கட்டுப்பாட்டகம்", "earnings": "வருவாய்", "incoming_jobs": "வரும் வேலைகள்",
        "profile": "சுயவிவரம்", "availability": "கிடைக்கும் நிலை", "reviews": "மதிப்புரைகள்", 
        "navigation": "வழிசெலுத்தல்", "logout": "வெளியேறு", "welcome": "தொழிலாளர் கட்டுப்பாட்டகம்",
        "performance_overview": "வரவேற்கிறோம்! உங்கள் செயல்திறன் அறிக்கை.", "total_jobs": "மொத்த வேலைகள்",
        "completed_jobs": "முடிக்கப்பட்ட வேலைகள்", "pending_jobs": "நிலுவையில் உள்ள வேலைகள்", "avg_rating": "சராசரி மதிப்பீடு",
        "total_earnings": "மொத்த வருவாய்", "quick_actions": "விரைவான செயல்கள்", "edit_profile": "சுயவிவரத்தை திருத்து",
        "set_availability": "கிடைக்கும் நிலையை அமை", "recent_jobs": "சமீபத்திய வேலைகள்", "view_all": "அனைத்தையும் காண்க",
        "save_profile": "சுயவிவரத்தை சேமி", "full_name": "முழு பெயர்", "skills": "திறன்கள்", 
        "experience": "அனுபவம்", "hourly_rate": "மணிநேர கட்டணம்", "languages": "மொழிகள்", "bio": "சுய குறிப்பு",
        "update_profile_desc": "வாடிக்கையாளர்களை ஈர்க்க உங்கள் விவரங்களை மேம்படுத்தவும்.",
        "active_status": "செயல்படும் நிலை", "available": "கிடைக்கும்", "unavailable": "கிடைக்கவில்லை",
        "offline": "ஆஃப்லைன்", "working_hours": "விருப்பமான வேலை நேரங்கள்", "save_settings": "அமைப்புகளைச் சேமி",
        "accept": "ஏற்றுக்கொள்", "reject": "நிராகரி", "new_requests": "உங்கள் திறன்களுக்கு பொருந்திய புதிய கோரிக்கைகள்.",
        "this_month": "இந்த மாதம்", "customer_reviews": "வாடிக்கையாளர் மதிப்புரைகள்", "verified": "சரிபார்க்கப்பட்டது",
        "customer": "வாடிக்கையாளர்", "voice_command_hint": "'வருவாய் திற' என்று சொல்லவும்",
        "listening": "கேட்கிறது...", "voice_not_supported": "உங்கள் உலாவி குரலை ஆதரிக்கவில்லை.",
        "good_morning": "காலை வணக்கம்", "daily_overview": "உங்கள் இன்றைய கண்ணோட்டம் இதோ",
        "receive_nearby_jobs": "அருகிலுள்ள வேலைகள் உங்களுக்கு வரும்", "currently_hidden": "நீங்கள் தற்போது மறைக்கப்பட்டுள்ளீர்கள்",
        "your_hub": "உங்கள் மையம்", "view_stats": "புள்ளிவிவரங்களைக் காண்க", "todays_earnings": "இன்றைய வருவாய்",
        "overall_rating": "மொத்த மதிப்பீடு", "on_the_way": "வழியில்", "navigate": "செல்லுங்கள்",
        "nearby_jobs": "அருகிலுள்ள வேலைகள்", "urgent": "அவசரம்", "distance": "தூரம்", "min": "நிமிடம்",
        "arrival": "வருகை", "exit_trip": "பயணத்தை வெளியேறு", "minimize": "சிறிதாக்கு", "completed": "முடிந்தது"
    },
    "bn": {
        "dashboard": "ড্যাশবোর্ড", "earnings": "উপার্জন", "incoming_jobs": "আগত চাকরি",
        "profile": "প্রোফাইল", "availability": "উপলব্ধতা", "reviews": "রিভিউ", 
        "navigation": "নেভিগেশন", "logout": "লগ আউট", "welcome": "কর্মী ড্যাশবোর্ড",
        "performance_overview": "স্বাগতম! আপনার পারফরম্যান্স সারাংশ।", "total_jobs": "মোট কাজ",
        "completed_jobs": "সম্পন্ন কাজ", "pending_jobs": "অমীমাংসিত কাজ", "avg_rating": "গড় রেটিং",
        "total_earnings": "সর্বমোট উপার্জন", "quick_actions": "দ্রুত পদক্ষেপ", "edit_profile": "প্রোফাইল সম্পাদনা",
        "set_availability": "উপলব্ধতা নির্ধারণ করুন", "recent_jobs": "সাম্প্রতিক কাজ", "view_all": "সবগুলো দেখুন",
        "save_profile": "প্রোফাইল সেভ করুন", "full_name": "পুরো নাম", "skills": "দক্ষতা", 
        "experience": "অভিজ্ঞতা", "hourly_rate": "প্রতি ঘণ্টার রেট", "languages": "ভাষা", "bio": "জীবনী",
        "update_profile_desc": "ক্লায়েন্ট আকর্ষণ করতে আপনার প্রোফাইল আপডেট করুন।",
        "active_status": "সক্রিয় অবস্থা", "available": "উপলব্ধ", "unavailable": "অনুপলব্ধ",
        "offline": "অফলাইন", "working_hours": "কাজের ঘণ্টা", "save_settings": "সেটিংস সংরক্ষণ করুন",
        "accept": "গ্রহণ করুন", "reject": "প্রত্যাখ্যান করুন", "new_requests": "আপনার দক্ষতার সাথে সামঞ্জস্যপূর্ণ নতুন চাকরির রিকোয়েস্ট।",
        "this_month": "চলতি মাস", "customer_reviews": "গ্রাহক পর্যালোচনা", "verified": "যাচাইকৃত",
        "customer": "গ্রাহক", "voice_command_hint": "বলার চেষ্টা করুন 'উপার্জন খুলুন'",
        "listening": "শুনছি...", "voice_not_supported": "আপনার ব্রাউজার ভয়েস সমর্থন করে না।",
        "good_morning": "সুপ্রভাত", "daily_overview": "আপনার দৈনিক সংক্ষিপ্তসার",
        "receive_nearby_jobs": "আপনি কাছের কাজ পাবেন", "currently_hidden": "আপনি বর্তমানে লুকানো আছেন",
        "your_hub": "আপনার হাব", "view_stats": "পরিসংখ্যান দেখুন", "todays_earnings": "আজকের উপার্জন",
        "overall_rating": "মোট রেটিং", "on_the_way": "পথে", "navigate": "নেভিগেট",
        "nearby_jobs": "কাছাকাছি কাজ", "urgent": "জরুরি", "distance": "দূরত্ব", "min": "মিনিট",
        "arrival": "আগমন", "exit_trip": "ট্রিপ শেষ করুন", "minimize": "ছোট করুন", "completed": "সম্পন্ন"
    },
    "gu": {
        "dashboard": "ડેશબોર્ડ", "earnings": "કમાણી", "incoming_jobs": "આવતી જોબ્સ",
        "profile": "પ્રોફાઇલ", "availability": "ઉપલબ્ધતા", "reviews": "સમીક્ષાઓ", 
        "navigation": "નેવિગેશન", "logout": "લૉગ આઉટ", "welcome": "વર્કર ડેશબોર્ડ",
        "performance_overview": "સ્વાગત છે! આ રહ્યો તમારો પ્રદર્શન રિપોર્ટ.", "total_jobs": "કુલ જોબ્સ",
        "completed_jobs": "પૂર્ણ થયેલ જોબ્સ", "pending_jobs": "બાકી જોબ્સ", "avg_rating": "સરેરાશ રેટિંગ",
        "total_earnings": "કુલ કમાણી", "quick_actions": "ત્વરિત ક્રિયાઓ", "edit_profile": "પ્રોફાઇલ સંપાદિત કરો",
        "set_availability": "ઉપલબ્ધતા સેટ કરો", "recent_jobs": "તાજેતરની જોબ્સ", "view_all": "બધા જુઓ",
        "save_profile": "પ્રોફાઇલ સાચવો", "full_name": "પૂરું નામ", "skills": "કૌશલ્યો", 
        "experience": "અનુભવ", "hourly_rate": "કલાકદીઠ દર", "languages": "ભાષાઓ", "bio": "પરિચય",
        "update_profile_desc": "વધુ ગ્રાહકોને આકર્ષવા માટે તમારી વિગતો અપડેટ કરો.",
        "active_status": "સક્રિય સ્થિતિ", "available": "ઉપલબ્ધ", "unavailable": "અનુપલબ્ધ",
        "offline": "ઑફલાઇન", "working_hours": "કામકાજના કલાકો", "save_settings": "સેટિંગ્સ સાચવો",
        "accept": "સ્વીકારો", "reject": "નકારો", "new_requests": "તમારી કુશળતા સાથે મેળ ખાતી નવી વિનંતીઓ.",
        "this_month": "આ મહિનો", "customer_reviews": "ગ્રાહક સમીક્ષાઓ", "verified": "ચકાસાયેલ",
        "customer": "ગ્રાહક", "voice_command_hint": "'કમાણી ખોલો' બોલીને પ્રયાસ કરો",
        "listening": "સાંભળી રહ્યું છે...", "voice_not_supported": "તમારું બ્રાઉઝર વૉઇસને સપોર્ટ કરતું નથી.",
        "good_morning": "સુપ્રભાત", "daily_overview": "અહીં તમારી દૈનિક ઝાંખી છે",
        "receive_nearby_jobs": "તમને નજીકની જોબ્સ મળશે", "currently_hidden": "તમે હાલમાં છુપાયેલ છો",
        "your_hub": "તમારું હબ", "view_stats": "આંકડા જુઓ", "todays_earnings": "આજની કમાણી",
        "overall_rating": "કુલ રેટિંગ", "on_the_way": "રસ્તામાં", "navigate": "નેવિગેટ કરો",
        "nearby_jobs": "નજીકની જોબ્સ", "urgent": "તાત્કાલિક", "distance": "અંતર", "min": "મિનિટ",
        "arrival": "આગમન", "exit_trip": "ટ્રિપમાંથી બહાર નીકળો", "minimize": "નાનું કરો", "completed": "પૂર્ણ થયું"
    },
    "kn": {
        "dashboard": "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್", "earnings": "ಗಳಿಕೆ", "incoming_jobs": "ಬರುವ ಕೆಲಸಗಳು",
        "profile": "ಪ್ರೊಫೈಲ್", "availability": "ಲಭ್ಯತೆ", "reviews": "ವಿಮರ್ಶೆಗಳು", 
        "navigation": "ನ್ಯಾವಿಗೇಶನ್", "logout": "ಲಾಗ್ ಔಟ್", "welcome": "ವರ್ಕರ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
        "performance_overview": "ಸ್ವಾಗತ! ನಿಮ್ಮ ಕಾರ್ಯಕ್ಷಮತೆಯ ವರದಿ ಇಲ್ಲಿದೆ.", "total_jobs": "ಒಟ್ಟು ಕೆಲಸಗಳು",
        "completed_jobs": "ಪೂರ್ಣಗೊಂಡ ಕೆಲಸಗಳು", "pending_jobs": "ಬಾಕಿ ಕೆಲಸಗಳು", "avg_rating": "ಸರಾಸರಿ ರೇಟಿಂಗ್",
        "total_earnings": "ಒಟ್ಟು ಗಳಿಕೆ", "quick_actions": "ತ್ವರಿತ ಕ್ರಿಯೆಗಳು", "edit_profile": "ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ",
        "set_availability": "ಲಭ್ಯತೆಯನ್ನು ಹೊಂದಿಸಿ", "recent_jobs": "ಇತ್ತೀಚಿನ ಕೆಲಸಗಳು", "view_all": "ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ",
        "save_profile": "ಪ್ರೊಫೈಲ್ ಉಳಿಸಿ", "full_name": "ಪೂರ್ಣ ಹೆಸರು", "skills": "ಕೌಶಲ್ಯಗಳು", 
        "experience": "ಅನುಭವ", "hourly_rate": "ಗಂಟೆಯ ದರ", "languages": "ಭಾಷೆಗಳು", "bio": "ಪರಿಚಯ",
        "update_profile_desc": "ಗ್ರಾಹಕರನ್ನು ಆಕರ್ಷಿಸಲು ನಿಮ್ಮ ವಿವರಗಳನ್ನು ನವೀಕರಿಸಿ.",
        "active_status": "ಸಕ್ರಿಯ ಸ್ಥಿತಿ", "available": "ಲಭ್ಯವಿದೆ", "unavailable": "ಲಭ್ಯವಿಲ್ಲ",
        "offline": "ಆಫ್‌ಲೈನ್", "working_hours": "ಕೆಲಸದ ಸಮಯ", "save_settings": "ಸೆಟ್ಟಿಂಗ್ಸ್ ಉಳಿಸಿ",
        "accept": "ಸ್ವೀಕರಿಸಿ", "reject": "ತಿರಸ್ಕರಿಸಿ", "new_requests": "ನಿಮ್ಮ ಕೌಶಲ್ಯಗಳಿಗೆ ಸರಿಹೊಂದುವ ಹೊಸ ವಿನಂತಿಗಳು.",
        "this_month": "ಈ ತಿಂಗಳು", "customer_reviews": "ಗ್ರಾಹಕರ ವಿಮರ್ಶೆಗಳು", "verified": "ಪರಿಶೀಲಿಸಲಾಗಿದೆ",
        "customer": "ಗ್ರಾಹಕ", "voice_command_hint": "'ಗಳಿಕೆ ತೆರೆಯಿರಿ' ಎಂದು ಹೇಳಿ",
        "listening": "ಆಲಿಸುತ್ತಿದೆ...", "voice_not_supported": "ನಿಮ್ಮ ಬ್ರೌಸರ್ ಧ್ವನಿಯನ್ನು ಬೆಂಬಲಿಸುವುದಿಲ್ಲ.",
        "good_morning": "ಶುಭೋದಯ", "daily_overview": "ನಿಮ್ಮ ವಾಡಿಕೆಯ ಅವಲೋಕನ ಇಲ್ಲಿದೆ",
        "receive_nearby_jobs": "ಹತ್ತಿರದ ಕೆಲಸಗಳನ್ನು ನೀವು ಪಡೆಯುತ್ತೀರಿ", "currently_hidden": "ನೀವು ಪ್ರಸ್ತುತ ಗುಪ್ತವಾಗಿದ್ದೀರಿ",
        "your_hub": "ನಿಮ್ಮ ಹಬ್", "view_stats": "ಅಂಕಿಅಂಶಗಳನ್ನು ವೀಕ್ಷಿಸಿ", "todays_earnings": "ಇಂದಿನ ಗಳಿಕೆ",
        "overall_rating": "ಒಟ್ಟಾರೆ ರೇಟಿಂಗ್", "on_the_way": "ದಾರಿಯಲ್ಲಿ", "navigate": "ನಾವಿಗೇಟ್ ಮಾಡಿ",
        "nearby_jobs": "ಹತ್ತಿರದ ಕೆಲಸಗಳು", "urgent": "ತುರ್ತು", "distance": "ದೂರ", "min": "ನಿಮಿಷ",
        "arrival": "ಆಗಮನ", "exit_trip": "ಟ್ರಿಪ್‌ನಿಂದ ನಿರ್ಗಮಿಸಿ", "minimize": "ಕಡಿಮೆಗೊಳಿಸಿ", "completed": "ಪೂರ್ಣಗೊಂಡಿದೆ"
    },
    "ml": {
        "dashboard": "ഡാഷ്ബോർഡ്", "earnings": "വരുമാനം", "incoming_jobs": "വരുന്ന ജോലികൾ",
        "profile": "പ്രൊഫൈൽ", "availability": "ലഭ്യത", "reviews": "അവലോകനങ്ങൾ", 
        "navigation": "നാവിഗേഷൻ", "logout": "ലോഗ് ഔട്ട്", "welcome": "വർക്കർ ഡാഷ്‌ബോർഡ്",
        "performance_overview": "സ്വാഗതം! നിങ്ങളുടെ പ്രകടന റിപ്പോർട്ട് ഇതാ.", "total_jobs": "മൊത്തം ജോലികൾ",
        "completed_jobs": "പൂർത്തിയാക്കിയ ജോലികൾ", "pending_jobs": "ബാക്കിയുള്ള ജോലികൾ", "avg_rating": "ശരാശരി റേറ്റിംഗ്",
        "total_earnings": "ആകെ വരുമാനം", "quick_actions": "ദ്രുത പ്രവർത്തനങ്ങൾ", "edit_profile": "പ്രൊഫൈൽ എഡിറ്റ് ചെയ്യുക",
        "set_availability": "ലഭ്യത സജ്ജീകരിക്കുക", "recent_jobs": "സമീപകാല ജോലികൾ", "view_all": "എല്ലാം കാണുക",
        "save_profile": "പ്രൊഫൈൽ സംരക്ഷിക്കുക", "full_name": "പൂർണ്ണമായ പേര്", "skills": "കഴിവുകൾ", 
        "experience": "പരിചയം", "hourly_rate": "മണിക്കൂർ നിരക്ക്", "languages": "ഭാഷകൾ", "bio": "വിവരണം",
        "update_profile_desc": "ഉപഭോക്താക്കളെ ആകർഷിക്കാൻ നിങ്ങളുടെ വിവരങ്ങൾ പരിഷ്കരിക്കുക.",
        "active_status": "സജീവ അവസ്ഥ", "available": "ലഭ്യമാണ്", "unavailable": "ലഭ്യമല്ല",
        "offline": "ഓഫ്‌ലൈൻ", "working_hours": "ജോലി സമയങ്ങൾ", "save_settings": "സജ്ജീകരണങ്ങൾ സംരക്ഷിക്കുക",
        "accept": "സ്വീകരിക്കുക", "reject": "നിരസിക്കുക", "new_requests": "നിങ്ങളുടെ കഴിവുകൾക്ക് അനുയോജ്യമായ പുതിയ അഭ്യർത്ഥനകൾ.",
        "this_month": "ഈ മാസം", "customer_reviews": "ഉപഭോക്തൃ അവലോകനങ്ങൾ", "verified": "സ്ഥിരീകരിച്ചു",
        "customer": "ഉപഭോക്താവ്", "voice_command_hint": "'വരുമാനം തുറക്കുക' എന്ന് പറയുക",
        "listening": "ശ്രദ്ധിക്കുന്നു...", "voice_not_supported": "നിങ്ങളുടെ ബ്രൗസർ വോയ്‌സിനെ പിന്തുണയ്ക്കുന്നില്ല.",
        "good_morning": "സുപ്രഭാതം", "daily_overview": "നിങ്ങളുടെ പ്രതിദിന അവലോകനം ഇതാ",
        "receive_nearby_jobs": "നിങ്ങൾക്ക് സമീപത്തെ ജോലികൾ ലഭിക്കും", "currently_hidden": "നിങ്ങൾ നിലവിൽ മറഞ്ഞിരിക്കുകയാണ്",
        "your_hub": "നിങ്ങളുടെ ഹബ്", "view_stats": "സ്ഥിതിവിവരക്കണക്കുകൾ കാണുക", "todays_earnings": "ഇന്നത്തെ വരുമാനം",
        "overall_rating": "മൊത്തത്തിലുള്ള റേറ്റിംഗ്", "on_the_way": "വഴിയിൽ", "navigate": "നാവിഗേറ്റ് ചെയ്യുക",
        "nearby_jobs": "സമീപത്തെ ജോലികൾ", "urgent": "അടിയന്തിരം", "distance": "ദൂരം", "min": "മിനിറ്റ്",
        "arrival": "എത്തിച്ചേരൽ", "exit_trip": "യാത്ര അവസാനിക്കുക", "minimize": "ചെറുതാക്കുക", "completed": "പൂർത്തിയായി"
    }
}


output = "export const translations = " + json.dumps(languages, indent=2, ensure_ascii=False) + ";\n"
output += "\n// TODO: Replace with backend-driven translation service if required\n"

with open(r"d:\LOC 8.0\Unisquad_LOC8W1\Unisquad_LOC8W1_Final\frontend\src\utils\translations.js", "w", encoding="utf-8") as f:
    f.write(output)
