import json

en_tabs = {
    "based_on_reviews": "Based on 98 reviews", "recent_reviews": "Recent Reviews",
    "earnings_history": "Earnings History", "paid": "paid",
    "search_jobs": "Search jobs...", "job_history": "Job History", "accept_job": "Accept Job", "view_details": "View Details",
    "schedule": "Schedule", "upcoming": "Upcoming",
    "contact_info": "Contact Information", "email": "Email", "phone": "Phone", "location": "Location",
    "skills_expertise": "Skills & Expertise", "total_reviews": "Total Reviews",
    "settings": "Settings", "notifications": "Notifications", "job_alerts": "Job Alerts", "job_alerts_desc": "Get notified about nearby jobs",
    "message_notifications": "Message Notifications", "message_notifs_desc": "Receive messages from employers",
    "earnings_updates": "Earnings Updates", "earn_updates_desc": "Get notified when payments are received",
    "preferences": "Preferences", "dark_mode": "Dark Mode", "dark_mode_desc": "Enable dark theme",
    "change": "Change", "privacy_security": "Privacy & Security", "change_password": "Change Password",
    "privacy_policy": "Privacy Policy", "terms_service": "Terms of Service", "help_support": "Help & Support",
    "faq": "FAQ", "contact_support": "Contact Support", "report_problem": "Report a Problem", "delete_account": "Delete Account"
}

hi_tabs = {"based_on_reviews": "98 समीक्षाओं पर आधारित", "recent_reviews": "हाल की समीक्षाएं", "earnings_history": "कमाई का इतिहास", "paid": "भुगतान किया", "search_jobs": "काम खोजें...", "job_history": "काम का इतिहास", "accept_job": "काम स्वीकार करें", "view_details": "विवरण देखें", "schedule": "अनुसूची", "upcoming": "आगामी", "contact_info": "संपर्क जानकारी", "email": "ईमेल", "phone": "फ़ोन", "location": "स्थान", "skills_expertise": "कौशल और विशेषज्ञता", "total_reviews": "कुल समीक्षाएं", "settings": "सेटिंग्स", "notifications": "सूचनाएं", "job_alerts": "जॉब अलर्ट", "job_alerts_desc": "आस-पास के काम के बारे में सूचना पाएं", "message_notifications": "संदेश सूचनाएं", "message_notifs_desc": "नियोक्ताओं से संदेश प्राप्त करें", "earnings_updates": "कमाई अपडेट", "earn_updates_desc": "भुगतान प्राप्त होने पर सूचना पाएं", "preferences": "प्राथमिकताएं", "dark_mode": "डार्क मोड", "dark_mode_desc": "डार्क थीम सक्षम करें", "change": "बदलें", "privacy_security": "गोपनीयता और सुरक्षा", "change_password": "पासवर्ड बदलें", "privacy_policy": "गोपनीयता नीति", "terms_service": "सेवा की शर्तें", "help_support": "सहायता और समर्थन", "faq": "सामान्य प्रश्न", "contact_support": "समर्थन से संपर्क करें", "report_problem": "समस्या की रिपोर्ट करें", "delete_account": "खाता हटाएं"}
mr_tabs = {"based_on_reviews": "98 पुनरावलोकनांवर आधारित", "recent_reviews": "अलीकडील पुनरावलोकने", "earnings_history": "कमाईचा इतिहास", "paid": "पैसे दिले", "search_jobs": "नोकऱ्या शोधा...", "job_history": "नोकरीचा इतिहास", "accept_job": "काम स्वीकारा", "view_details": "तपशील पहा", "schedule": "वेळापत्रक", "upcoming": "आगामी", "contact_info": "संपर्क माहिती", "email": "ईमेल", "phone": "फोन", "location": "स्थान", "skills_expertise": "कौशल्य आणि कौशल्य", "total_reviews": "एकूण पुनरावलोकने", "settings": "सेटिंग्ज", "notifications": "सूचना", "job_alerts": "जॉब अलर्ट", "job_alerts_desc": "जवळील कामांबद्दल सूचना मिळवा", "message_notifications": "संदेश सूचना", "message_notifs_desc": "मालकांकडून संदेश मिळवा", "earnings_updates": "कमाईचे अपडेट", "earn_updates_desc": "पैसे मिळाल्यावर सूचना मिळवा", "preferences": "प्राधान्ये", "dark_mode": "डार्क मोड", "dark_mode_desc": "डार्क थीम सक्षम करा", "change": "बदला", "privacy_security": "गोपनीयता आणि सुरक्षा", "change_password": "पासवर्ड बदला", "privacy_policy": "गोपनीयता धोरण", "terms_service": "सेवा अटी", "help_support": "मदत आणि समर्थन", "faq": "वारंवार विचारले जाणारे प्रश्न", "contact_support": "अधिक माहितीसाठी संपर्क साधा", "report_problem": "समस्येची तक्रार करा", "delete_account": "खाते हटवा"}
te_tabs = {"based_on_reviews": "98 సమీక్షల ఆధారంగా", "recent_reviews": "ఇటీవలి సమీక్షలు", "earnings_history": "ఆదాయ చరిత్ర", "paid": "చెల్లించబడింది", "search_jobs": "పనులను వెతకండి...", "job_history": "పని చరిత్ర", "accept_job": "పని అంగీకరించు", "view_details": "వివరాలు చూడండి", "schedule": "షెడ్యూల్", "upcoming": "రానున్న", "contact_info": "సంప్రదింపు సమాచారం", "email": "ఇమెయిల్", "phone": "ఫోన్", "location": "ప్రదేశం", "skills_expertise": "నైపుణ్యాలు", "total_reviews": "మొత్తం సమీక్షలు", "settings": "సెట్టింగులు", "notifications": "నోటిఫికేషన్‌లు", "job_alerts": "జాబ్ అలెర్ట్స్", "job_alerts_desc": "సమీప పనుల గురించి నోటిఫికేషన్ పొందండి", "message_notifications": "సందేశ నోటిఫికేషన్‌లు", "message_notifs_desc": "యజమానుల నుండి సందేశాలను పొందండి", "earnings_updates": "ఆదాయాల నవీకరణలు", "earn_updates_desc": "చెల్లింపులు జరిగినప్పుడు నోటిఫికేషన్ పొందండి", "preferences": "ప్రాధాన్యతలు", "dark_mode": "డార్క్ మోడ్", "dark_mode_desc": "డార్క్ థీమ్ ప్రారంభించు", "change": "మార్చు", "privacy_security": "గోప్యత మరియు భద్రత", "change_password": "పాస్‌వర్డ్ మార్చండి", "privacy_policy": "గోప్యతా విధానం", "terms_service": "సేవా నిబంధనలు", "help_support": "సహాయం", "faq": "పదే పదే అడిగే ప్రశ్నలు", "contact_support": "సపోర్ట్ ను సంప్రదించండి", "report_problem": "సమస్యను నివేదించండి", "delete_account": "ఖాతా తొలగించు"}
ta_tabs = {"based_on_reviews": "98 மதிப்புரைகளின் அடிப்படையில்", "recent_reviews": "சமீபத்திய மதிப்புரைகள்", "earnings_history": "வருவாய் வரலாறு", "paid": "செலுத்தப்பட்டது", "search_jobs": "வேலைகளைத் தேடு...", "job_history": "வேலை வரலாறு", "accept_job": "வேலையை ஏற்றுக்கொள்", "view_details": "விவரங்களை பார்க்க", "schedule": "அட்டவணை", "upcoming": "எதிர்வரும்", "contact_info": "தொடர்புத் தகவல்", "email": "மின்னஞ்சல்", "phone": "தொலைபேசி", "location": "இடம்", "skills_expertise": "திறன்கள்", "total_reviews": "மொத்த மதிப்புரைகள்", "settings": "அமைப்புகள்", "notifications": "அறிவிப்புகள்", "job_alerts": "வேலை எச்சரிக்கைகள்", "job_alerts_desc": "அருகிலுள்ள வேலைகளைப் பற்றிய அறிவிப்புகளைப் பெறுங்கள்", "message_notifications": "செய்தி அறிவிப்புகள்", "message_notifs_desc": "பணியமர்த்துபவர்களிடமிருந்து செய்திகளைப் பெறுங்கள்", "earnings_updates": "வருவாய் புதுப்பிப்புகள்", "earn_updates_desc": "பணம் பெறும்போது அறிவிப்பைப் பெறுங்கள்", "preferences": "விருப்பங்கள்", "dark_mode": "டார்க் மோட்", "dark_mode_desc": "இருண்ட கருப்பொருளை இயக்கு", "change": "மாற்று", "privacy_security": "தனியுரிமை & பாதுகாப்பு", "change_password": "கடவுச்சொல்லை மாற்று", "privacy_policy": "தனியுரிமைக் கொள்கை", "terms_service": "சேவை விதிமுறைகள்", "help_support": "உதவி & ஆதரவு", "faq": "அடிக்கடி கேட்கப்படும் கேள்விகள்", "contact_support": "ஆதரவை தொடர்பு கொள்ளவும்", "report_problem": "பிரச்சனையை புகாரளிக்கவும்", "delete_account": "கணக்கை நீக்கு"}
bn_tabs = {"based_on_reviews": "98 পর্যালোচনার উপর ভিত্তি করে", "recent_reviews": "সাম্প্রতিক রিভিউ", "earnings_history": "উপার্জনের ইতিহাস", "paid": "প্রদান করা হয়েছে", "search_jobs": "চাকরি খুঁজুন...", "job_history": "কাজের ইতিহাস", "accept_job": "কাজ গ্রহণ করুন", "view_details": "বিস্তারিত দেখুন", "schedule": "সূচি", "upcoming": "আসন্ন", "contact_info": "যোগাযোগের তথ্য", "email": "ইমেইল", "phone": "ফোন", "location": "অবস্থান", "skills_expertise": "দক্ষতা", "total_reviews": "মোট রিভিউ", "settings": "সেটিংস", "notifications": "বিজ্ঞপ্তি", "job_alerts": "জব অ্যালার্ট", "job_alerts_desc": "কাছের কাজ সম্পর্কে বিজ্ঞপ্তি পান", "message_notifications": "মেসেজ নোটিফিকেশন", "message_notifs_desc": "নিয়োগকারীদের থেকে বার্তা পান", "earnings_updates": "উপার্জন আপডেট", "earn_updates_desc": "পেমেন্ট পেলে বিজ্ঞপ্তি পান", "preferences": "পছন্দসমূহ", "dark_mode": "ডার্ক মোড", "dark_mode_desc": "ডার্ক থিম সক্ষম করুন", "change": "পরিবর্তন করুন", "privacy_security": "গোপনীয়তা ও নিরাপত্তা", "change_password": "পাসওয়ার্ড পরিবর্তন করুন", "privacy_policy": "গোপনীয়তা নীতি", "terms_service": "পরিষেবার শর্তাবলী", "help_support": "সাহায্য ও সাপোর্ট", "faq": "প্রায়শই জিজ্ঞাসিত প্রশ্ন", "contact_support": "যোগাযোগ করুন", "report_problem": "সমস্যার কথা জানান", "delete_account": "অ্যাকাউন্ট মুছুন"}
gu_tabs = {"based_on_reviews": "98 સમીક્ષાઓના આધારે", "recent_reviews": "તાજેતરની સમીક્ષાઓ", "earnings_history": "કમાણીનો ઇતિહાસ", "paid": "ચૂકવેલ", "search_jobs": "જોબ્સ શોધો...", "job_history": "જોબ ઇતિહાસ", "accept_job": "જોબ સ્વીકારો", "view_details": "વિગતો જુઓ", "schedule": "અનુસૂચિ", "upcoming": "આગામી", "contact_info": "સંપર્ક માહિતી", "email": "ઇમેઇલ", "phone": "ફોન", "location": "સ્થાન", "skills_expertise": "કૌશલ્યો", "total_reviews": "કુલ સમીક્ષાઓ", "settings": "સેટિંગ્સ", "notifications": "સૂચનાઓ", "job_alerts": "જોબ ચેતવણીઓ", "job_alerts_desc": "નજીકની જોબ્સ વિશે સૂચના મેળવો", "message_notifications": "સંદેશ સૂચનાઓ", "message_notifs_desc": "માલિકો તરફથી સંદેશાઓ મેળવો", "earnings_updates": "કમાણી અપડેટ્સ", "earn_updates_desc": "ચૂકવણીઓ મળવા પર સૂચના મેળવો", "preferences": "પસંદગીઓ", "dark_mode": "ડાર્ક મોડ", "dark_mode_desc": "ડાર્ક થીમ સક્રિય કરો", "change": "બદલો", "privacy_security": "ગોપનીયતા અને સુરક્ષા", "change_password": "પાસવર્ડ બદલો", "privacy_policy": "ગોપનીયતા નીતિ", "terms_service": "સેવાની શરતો", "help_support": "સહાય અને સપોર્ટ", "faq": "વારંવાર પૂછાતા પ્રશ્નો", "contact_support": "સપોર્ટનો સંપર્ક કરો", "report_problem": "સમસ્યાની જાણ કરો", "delete_account": "એકાઉન્ટ કાઢી નાખો"}
kn_tabs = {"based_on_reviews": "98 ವಿಮರ್ಶೆಗಳ ಆಧಾರದ ಮೇಲೆ", "recent_reviews": "ಇತ್ತೀಚಿನ ವಿಮರ್ಶೆಗಳು", "earnings_history": "ಗಳಿಕೆಯ ಇತಿಹಾಸ", "paid": "ಪಾವತಿಸಲಾಗಿದೆ", "search_jobs": "ಕೆಲಸಗಳನ್ನು ಹುಡುಕಿ...", "job_history": "ಕೆಲಸದ ಇತಿಹಾಸ", "accept_job": "ಕೆಲಸ ಸ್ವೀಕರಿಸಿ", "view_details": "ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ", "schedule": "ವೇಳಾಪಟ್ಟಿ", "upcoming": "ಮುಂಬರುವ", "contact_info": "ಸಂಪರ್ಕ ಮಾಹಿತಿ", "email": "ಇಮೇಲ್", "phone": "ಫೋನ್", "location": "ಸ್ಥಳ", "skills_expertise": "ಕೌಶಲ್ಯಗಳು", "total_reviews": "ಒಟ್ಟು ವಿಮರ್ಶೆಗಳು", "settings": "ಸೆಟ್ಟಿಂಗ್ಸ್", "notifications": "ಅಧಿಸೂಚನೆಗಳು", "job_alerts": "ಜಾಬ್ ಅಲರ್ಟ್ಸ್", "job_alerts_desc": "ಹತ್ತಿರದ ಕೆಲಸಗಳ ಬಗ್ಗೆ ಅಧಿಸೂಚನೆ ಪಡೆಯಿರಿ", "message_notifications": "ಸಂದೇಶ ಅಧಿಸೂಚನೆಗಳು", "message_notifs_desc": "ಉದ್ಯೋಗದಾತರಿಂದ ಸಂದೇಶಗಳನ್ನು ಪಡೆಯಿರಿ", "earnings_updates": "ಗಳಿಕೆಯ ನವೀಕರಣಗಳು", "earn_updates_desc": "ಪಾವತಿಗಳನ್ನು ಸ್ವೀಕರಿಸಿದಾಗ ಅಧಿಸೂಚನೆ ಪಡೆಯಿರಿ", "preferences": "ಪ್ರಾಶಸ್ತ್ಯಗಳು", "dark_mode": "ಡಾರ್ಕ್ ಮೋಡ್", "dark_mode_desc": "ಡಾರ್ಕ್ ಥೀಮ್ ಸಕ್ರಿಯಗೊಳಿಸಿ", "change": "ಬದಲಾಯಿಸಿ", "privacy_security": "ಗೌಪ್ಯತೆ ಮತ್ತು ಭದ್ರತೆ", "change_password": "ಪಾಸ್ವರ್ಡ್ ಬದಲಾಯಿಸಿ", "privacy_policy": "ಗೌಪ್ಯತಾ ನೀತಿ", "terms_service": "ಸೇವಾ ನಿಯಮಗಳು", "help_support": "ಸಹಾಯ ಮತ್ತು ಬೆಂಬಲ", "faq": "ಸಾಮಾನ್ಯವಾಗಿ ಕೇಳಲಾಗುವ ಪ್ರಶ್ನೆಗಳು", "contact_support": "ಬೆಂಬಲವನ್ನು ಸಂಪರ್ಕಿಸಿ", "report_problem": "ಸಮಸ್ಯೆಯನ್ನು ವರದಿ ಮಾಡಿ", "delete_account": "ಖಾತೆಯನ್ನು ಅಳಿಸಿ"}
ml_tabs = {"based_on_reviews": "98 അവലോകനങ്ങളുടെ അടിസ്ഥാനത്തിൽ", "recent_reviews": "സമീപകാല അവലോകനങ്ങൾ", "earnings_history": "വരുമാന ചരിത്രം", "paid": "പണം നൽകി", "search_jobs": "ജോലികൾ തിരയുക...", "job_history": "ജോലി ചരിത്രം", "accept_job": "ജോലി സ്വീകരിക്കുക", "view_details": "വിശദാംശങ്ങൾ കാണുക", "schedule": "പട്ടിക", "upcoming": "വരാനിരിക്കുന്ന", "contact_info": "ബന്ധപ്പെടാനുള്ള വിവരങ്ങൾ", "email": "ഇമെയിൽ", "phone": "ഫോൺ", "location": "സ്ഥലം", "skills_expertise": "കഴിവുകൾ", "total_reviews": "മൊത്തം അവലോകനങ്ങൾ", "settings": "സജ്ജീകരണങ്ങൾ", "notifications": "അറിയിപ്പുകൾ", "job_alerts": "ജോലി അലേർട്ടുകൾ", "job_alerts_desc": "സമീപത്തെ ജോലികളെക്കുറിച്ച് അറിയിപ്പ് നേടുക", "message_notifications": "സന്ദേശ അറിയിപ്പുകൾ", "message_notifs_desc": "തൊഴിലുടമകളിൽ നിന്ന് സന്ദേശങ്ങൾ നേടുക", "earnings_updates": "വരുമാന അപ്‌ഡേറ്റുകൾ", "earn_updates_desc": "പണം ലഭിക്കുമ്പോൾ അറിയിപ്പ് നേടുക", "preferences": "മുൻഗണനകൾ", "dark_mode": "ഡാർക്ക് മോഡ്", "dark_mode_desc": "ഡാർക്ക് തീം പ്രവർത്തനക്ഷമമാക്കുക", "change": "മാറ്റുക", "privacy_security": "സ്വകാര്യതയും സുരക്ഷയും", "change_password": "പാസ്‌വേഡ് മാറ്റുക", "privacy_policy": "സ്വകാര്യതാ നയം", "terms_service": "സേവന നിബന്ധനകൾ", "help_support": "സഹായവും പിന്തുണയും", "faq": "പതിവുചോദ്യങ്ങൾ", "contact_support": "പിന്തുണയുമായി ബന്ധപ്പെടുക", "report_problem": "ഒരു പ്രശ്നം റിപ്പോർട്ട് ചെയ്യുക", "delete_account": "അക്കൗണ്ട് ഇല്ലാതാക്കുക"}


with open(r"d:\LOC 8.0\Unisquad_LOC8W1\Unisquad_LOC8W1_Final\frontend\src\utils\translations.js", "r", encoding="utf-8") as f:
    content = f.read()

import ast

# Hack to inject easily: Since I structured my previous generator file simply, I can do it via regex or just write the raw dict code locally.
import json
with open(r"d:\LOC 8.0\Unisquad_LOC8W1\Unisquad_LOC8W1_Final\backend\gen_trans_full.py", "w", encoding="utf-8") as fw:
    pass

import sys
sys.path.append(r"d:\LOC 8.0\Unisquad_LOC8W1\Unisquad_LOC8W1_Final\backend")
import gen_trans

langs = gen_trans.languages
langs["en"].update(en_tabs)
langs["hi"].update(hi_tabs)
langs["mr"].update(mr_tabs)
langs["te"].update(te_tabs)
langs["ta"].update(ta_tabs)
langs["bn"].update(bn_tabs)
langs["gu"].update(gu_tabs)
langs["kn"].update(kn_tabs)
langs["ml"].update(ml_tabs)

output = "export const translations = " + json.dumps(langs, indent=2, ensure_ascii=False) + ";\n"
output += "\n// TODO: Replace with backend-driven translation service if required\n"
with open(r"d:\LOC 8.0\Unisquad_LOC8W1\Unisquad_LOC8W1_Final\frontend\src\utils\translations.js", "w", encoding="utf-8") as f:
    f.write(output)

